spring:
  application:
    name: muse
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb

jwt:
  access-token-expiration-day: 10
  secret-key: a29waXMtYmlnLWRhdGEtbXVzZQ==