spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muse
    username: muse
    password: muse
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  access-token-expiration-day: 10
  secret-key: a29waXMtYmlnLWRhdGEtbXVzZQ==

